# Generated by Django 3.2.7 on 2021-10-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_profil_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profil_photo',
        ),
    ]
